name: bash-actions

on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a script
        run: mkdir Hello
        shell: bash